// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "spinner":return img`
........................
........................
........................
..........ffff..........
........ff8888ff........
.......f98888889f.......
......f968888888f.......
......f6688888886f......
......f6668888886f......
......f6666668886f......
......f6666668886f......
......f6666666686f......
......ff66669f686f......
.......f96669f669f......
.......fff66699ffff.....
.......ffff9f666869f....
......ffffffff96868f....
...ffffffffff..f6f8f....
.....ffffff.....f.f.....
........................
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
