def on_overlap_tile(sprite, location):
    game.over(False)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.hazard_lava0,
    on_overlap_tile)

def on_overlap_tile2(sprite2, location2):
    game.over(True)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        myTile4
    """),
    on_overlap_tile2)

def on_overlap_tile3(sprite22, location22):
    game.over(False)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.collectible_insignia,
    on_overlap_tile3)

mySprite = sprites.create(assets.image("""
    spinner
"""), SpriteKind.player)
mySprite.start_effect(effects.cool_radial)
mySprite.start_effect(effects.halo)
mySprite.start_effect(effects.fountain)
mySprite.start_effect(effects.spray)
controller.move_sprite(mySprite, 100, 100)
tiles.set_tilemap(tilemap("""
    level2
"""))
tiles.place_on_random_tile(mySprite, assets.tile("""
    myTile3
"""))
scene.camera_follow_sprite(mySprite)
animation.run_image_animation(mySprite,
    [img("""
            ........................
                ........................
                ........................
                ........................
                ..........fffff.........
                ........ff88888f........
                .......f68888888f.......
                ......f668888888f.......
                ......f6668888888f......
                ......f6666888888f......
                ......f6666666888f......
                ......f6666669f88f......
                ......f666666cf88f......
                .......f6666888888f.....
                ........fff9f98889f.....
                .......ffffffff8f8f.....
                ....ff.fffffffffff......
                .....ffffffff...........
                .....ffffff9999f........
                ......ffffff9f9f........
                ........................
                ........................
                ........................
                ........................
        """),
        img("""
            ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff8888ff........
                .......f68888888f.......
                .......f68888888f.......
                ......f6688888888f......
                ......f6668888888f......
                ......f6666668888f......
                ......f666669f888f......
                ......f66666cf888f......
                .......f66989888f.......
                ........fffff889f.......
                ........f69998f8f.......
                ........ff6969ff........
                ......f.fff6f6f.........
                ......ffffffff..........
                .......fffff............
                ........................
                ........................
                ........................
                ........................
        """)],
    500,
    True)
info.start_countdown(240)
controller.move_sprite(mySprite, 100, 100)

def on_forever():
    music.play(music.string_playable("C5 B A G F E F A ", 120),
        music.PlaybackMode.IN_BACKGROUND)
forever(on_forever)
game