scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava0, function on_overlap_tile(sprite: Sprite, location: tiles.Location) {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`
        myTile4
    `, function on_overlap_tile2(sprite2: Sprite, location2: tiles.Location) {
    game.over(true)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleInsignia, function on_overlap_tile3(sprite22: Sprite, location22: tiles.Location) {
    game.over(false)
})
let mySprite = sprites.create(assets.image`
    spinner
`, SpriteKind.Player)
mySprite.startEffect(effects.coolRadial)
mySprite.startEffect(effects.halo)
mySprite.startEffect(effects.fountain)
mySprite.startEffect(effects.spray)
controller.moveSprite(mySprite, 100, 100)
tiles.setTilemap(tilemap`
    level2
`)
tiles.placeOnRandomTile(mySprite, assets.tile`
    myTile3
`)
scene.cameraFollowSprite(mySprite)
animation.runImageAnimation(mySprite, [img`
            ........................
                ........................
                ........................
                ........................
                ..........fffff.........
                ........ff88888f........
                .......f68888888f.......
                ......f668888888f.......
                ......f6668888888f......
                ......f6666888888f......
                ......f6666666888f......
                ......f6666669f88f......
                ......f666666cf88f......
                .......f6666888888f.....
                ........fff9f98889f.....
                .......ffffffff8f8f.....
                ....ff.fffffffffff......
                .....ffffffff...........
                .....ffffff9999f........
                ......ffffff9f9f........
                ........................
                ........................
                ........................
                ........................
        `, img`
            ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff8888ff........
                .......f68888888f.......
                .......f68888888f.......
                ......f6688888888f......
                ......f6668888888f......
                ......f6666668888f......
                ......f666669f888f......
                ......f66666cf888f......
                .......f66989888f.......
                ........fffff889f.......
                ........f69998f8f.......
                ........ff6969ff........
                ......f.fff6f6f.........
                ......ffffffff..........
                .......fffff............
                ........................
                ........................
                ........................
                ........................
        `], 500, true)
info.startCountdown(240)
controller.moveSprite(mySprite, 100, 100)
forever(function on_forever() {
    music.play(music.stringPlayable("C5 B A G F E F A ", 120), music.PlaybackMode.InBackground)
})
game
